main: main.cpp implementations/utils.cpp implementations/chatGPT.cpp implementations/estudiante.cpp implementations/dtfecha.cpp implementations/dtinfoestudiante.cpp implementations/informacion.cpp implementations/libro.cpp implementations/paginaWeb.cpp
	g++ main.cpp implementations/utils.cpp implementations/chatGPT.cpp implementations/estudiante.cpp implementations/dtfecha.cpp implementations/dtinfoestudiante.cpp implementations/informacion.cpp implementations/libro.cpp implementations/paginaWeb.cpp -o main

clean: 
	rm main
